## 🔹 Section 2: Indexing, Slicing & Masking (Q11–Q20)

11. Extract the last column from a 2D NumPy array.
12. Reverse a NumPy array without using loops.
13. Explain boolean indexing and its importance in data analysis.
14. Select all values greater than the mean of an array.
15. Replace all negative values in an array with zero.
16. Extract rows where total sales exceed a given threshold.
17. What is fancy indexing and how is it different from slicing?
18. Select elements at indices `[2, 5, 8, 11]` from a NumPy array.
19. Demonstrate the difference between a view and a copy in NumPy.
20. How do you apply multiple conditions when filtering a NumPy array?

In [38]:
import numpy as np

# Extract the last column from a 2D NumPy array.

In [39]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
a[:,3:]

array([[ 3],
       [ 7],
       [11]])

# Reverse a NumPy array without using loops.

In [41]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
b[::-1,::]

array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [43]:
b[::,::-1]

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8]])

# Explain boolean indexing and its importance in data analysis.

In [44]:
c = np.random.randint(1,100,25).reshape(5,5)
c

array([[87, 21, 47, 76, 61],
       [75, 93, 44, 45, 73],
       [61, 53, 70, 75, 67],
       [31, 87, 75, 19, 42],
       [83, 64, 79, 87, 31]], dtype=int32)

#### Boolean indexing is a technique used to filter, select, or modify data based on logical conditions (True / False). It is widely used in data analysis libraries such as Pandas and NumPy to work with subsets of data efficiently.

In [45]:
[c>50]

[array([[ True, False, False,  True,  True],
        [ True,  True, False, False,  True],
        [ True,  True,  True,  True,  True],
        [False,  True,  True, False, False],
        [ True,  True,  True,  True, False]])]

# Select all values greater than the mean of an array.

In [46]:
m = np.mean(c)
print("mean:",m)
print("Values that are greater than mean:\n",c[c > m])

mean: 61.84
Values that are greater than mean:
 [87 76 75 93 73 70 75 67 87 75 83 64 79 87]


# Replace all negative values in an array with zero.

In [47]:
b = np.random.randint(-10,10,20).reshape(5,4)
b

array([[  7,  -4,  -1,  -2],
       [ -5, -10,   8, -10],
       [  1,  -5,  -8,  -4],
       [  7,  -3,   7,   3],
       [  8,   6,  -4,   8]], dtype=int32)

In [48]:
b[b<0] = 0
b

array([[7, 0, 0, 0],
       [0, 0, 8, 0],
       [1, 0, 0, 0],
       [7, 0, 7, 3],
       [8, 6, 0, 8]], dtype=int32)

# Extract rows where total sales exceed a given threshold.

In [49]:
salary = np.array([10000,20000,400000,100000])

salary = salary[salary > 50000]
salary

array([400000, 100000])

# What is fancy indexing and how is it different from slicing?


- Fancy indexing in NumPy is a way to access array elements using an array or list of indices (or a boolean array), allowing selection of non-contiguous, arbitrary elements.

- Slicing, on the other hand, selects continuous ranges of elements using start:stop:step.

In [53]:
arr = np.array([10, 20, 30, 40, 50])

print("Slicing:",arr[1:4])        # Slicing → [20 30 40]
print("Fancy Indexing:",arr[[0, 2, 4]])  # Fancy indexing → [10 30 50]


Slicing: [20 30 40]
Fancy Indexing: [10 30 50]


# Select elements at indices `[2, 5, 8, 11]` from a NumPy array.

In [55]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [56]:
a[[2,5,8,11]]

array([ 2,  5,  8, 11])

# Demonstrate the difference between a view and a copy in NumPy.

- A view does not create new data. It only provides a different way to look at the same underlying array.

In [64]:
arr = np.array([10, 20, 30, 40, 50])

view_arr = arr[1:4]   # slicing → view
view_arr[0] = 999

print(arr)
print(view_arr)

[ 10 999  30  40  50]
[999  30  40]


# How do you apply multiple conditions when filtering a NumPy array?

In [74]:
arr = np.random.randint(-10,10,24).reshape(4,6)
arr

array([[ 5,  7, -3,  2,  8, -7],
       [ 4,  7,  3, -7, -5, -9],
       [ 4,  2,  0,  8, -4,  2],
       [ 7, -6, -2, -4, -5, -3]], dtype=int32)

In [82]:
result = arr[(arr>0) & (arr%2==0)]
result

array([2, 8, 4, 4, 2, 8, 2], dtype=int32)