## 🔹 Section 1: Core NumPy Fundamentals (Q1–Q10)

- Why is NumPy significantly faster than Python lists for numerical computation?
- Create a NumPy array containing values from 0 to 1,000 with a step size of 5.
- Explain the difference between `np.array()` and `np.asarray()`.
- How does NumPy store data in memory, and why does this matter for performance?
- Create a 3×5 NumPy array of random integers between 100 and 500.
- What is the purpose of NumPy data types (`dtype`)?
- Convert a float array into an integer array and analyze the impact on memory.
- How do you check the shape, size, and number of dimensions of a NumPy array?
- Create an identity matrix of size 6×6.
- When should you explicitly specify the `dtype` while creating a NumPy array?

# Why is NumPy significantly faster than Python lists for numerical computation?

- It has contigious memory storage - better CPU cache utilization
- Broadcasting is supported, which avoids creating unnecessary temporary array
- Uses homogeneous data types, with fixed sized 
- Supports vectorization, processing entire arrays at once
- Enables broadcasting without copying data
- Allows us the perform high level mathematics operations in ease

# Create a NumPy array containing values from 0 to 1,000 with a step size of 5.

In [1]:
# importing numpy
import numpy as np

In [ ]:
np.arange(0,1001,5)

array([   0,    5,   10,   15,   20,   25,   30,   35,   40,   45,   50,
         55,   60,   65,   70,   75,   80,   85,   90,   95,  100,  105,
        110,  115,  120,  125,  130,  135,  140,  145,  150,  155,  160,
        165,  170,  175,  180,  185,  190,  195,  200,  205,  210,  215,
        220,  225,  230,  235,  240,  245,  250,  255,  260,  265,  270,
        275,  280,  285,  290,  295,  300,  305,  310,  315,  320,  325,
        330,  335,  340,  345,  350,  355,  360,  365,  370,  375,  380,
        385,  390,  395,  400,  405,  410,  415,  420,  425,  430,  435,
        440,  445,  450,  455,  460,  465,  470,  475,  480,  485,  490,
        495,  500,  505,  510,  515,  520,  525,  530,  535,  540,  545,
        550,  555,  560,  565,  570,  575,  580,  585,  590,  595,  600,
        605,  610,  615,  620,  625,  630,  635,  640,  645,  650,  655,
        660,  665,  670,  675,  680,  685,  690,  695,  700,  705,  710,
        715,  720,  725,  730,  735,  740,  745,  7

# Explain the difference between `np.array()` and `np.asarray()`.
- `np.array()`: Always creates the new numpy array and (copy by default)
- Even if the input value is numpy array  
- It avoids modifying the original data 
- `np.asarray()`: Does not copy data if the input value is numpy array
- Creates view/reference when ever possible
- Faster and more-memory efficient

# How does NumPy store data in memory, and why does this matter for performance?
- NumPy arrays store elements in "contigeous" block of memory
- All elements are homogeneous(same) data type
- Better CPU cache utilization, where cache is store in lines ~ 64 bytes
- Supports views instead of copies - Multiple arrays can point to the same data.
- Uses row-major order by default - row operations are very fast
- Enables vectorized operations - operations are performed on complete array at once


# Create a 3×5 NumPy array of random integers between 100 and 500.

In [13]:
a = np.random.randint(100,500,(3,5))
a

array([[192, 358, 295, 165, 292],
       [271, 312, 161, 350, 470],
       [284, 450, 419, 319, 229]], dtype=int32)

# What is the purpose of NumPy data types (`dtype`)?
- dtype is nothing but the data type, it shows the data type of array
- Using the dtype, we can change the memory size of data type as well 
- How much memory each element uses

# Convert a float array into an integer array and analyze the impact on memory

In [29]:
a = np.arange(12,dtype=float).reshape(3,4)
a.itemsize

8

In [28]:
b = a.astype(np.dtype('int16'))
b.itemsize

2

# How do you check the shape, size, and number of dimensions of a NumPy array?

In [30]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
x.shape  # shape 

(3, 4)

In [ ]:
x.size   # size

12

In [ ]:
x.ndim  # number of dim

2

# Create an identity matrix of size 6×6.

In [43]:
y = np.identity(6)
print(y)
print(y.shape)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
(6, 6)


# When should you explicitly specify the `dtype` while creating a NumPy array?
- To control memory usage, Default integers/floats may use more memory than needed.
- To avoid unintended type inference, NumPy may infer an unexpected dtype.
- To improve performance, Smaller, fixed-size types fit better in CPU cache.
- When working with large datasets, Even small dtype changes significantly reduce memory.
