
## Section 3: Mathematical & Statistical Operations (Q21–Q30)

In [169]:
import numpy as np

# Compute the mean, median, and standard deviation of a dataset using NumPy.

In [170]:
m = np.random.randint(1,50,25).reshape(5,5)
m

array([[48, 25,  3, 24, 13],
       [12, 43,  4, 16,  2],
       [26, 47, 15, 19, 24],
       [32, 36, 48, 41, 49],
       [ 6, 33, 33, 10, 40]], dtype=int32)

In [171]:
m.mean()

np.float64(25.96)

# Calculate row-wise and column-wise sums of a 2D array.

In [172]:
arr = np.random.randint(1,50,12).reshape(4,3)
arr

array([[14, 24,  5],
       [18,  2, 43],
       [12, 29, 14],
       [13, 30, 18]], dtype=int32)

In [173]:
row_wise = arr.sum(axis=0)
row_wise

array([57, 85, 80])

In [174]:
col_wise = arr.sum(axis=1)
col_wise

array([43, 63, 55, 61])

# What is the difference between `np.sum()` and `np.cumsum()`?

` np.sum()`:

- Computes the total sum of elements

- Returns one value per axis (or a single scalar)

`np.cumsum()`:

- Computes the running (cumulative) sum

- Each element includes the sum of all previous elements

- Returns an array of the same shape

In [175]:
arr = np.array([1,2,3,4,5,6,7])
arr

array([1, 2, 3, 4, 5, 6, 7])

In [176]:
# np.sum()
arr.sum()

np.int64(28)

In [177]:
# np.cumsum() -> Cumlative sum --> adding previous number with present (e.g. fibonacci)

arr.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28])

# Normalize a NumPy array using Min-Max normalization.

In [178]:
arr = np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

### norm = X - X(min) / X(max) - X(min) --> Formula

In [179]:
val_min = arr.min()
val_max = arr.max()

norm = (arr-val_min) / (val_max-val_min)
norm

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# Compute variance and covariance using NumPy.


In [180]:
val = np.random.randint(1,25,12).reshape(4,3)
val

array([[ 6, 13, 11],
       [ 1,  4,  6],
       [ 9,  6,  5],
       [17,  1, 10]], dtype=int32)

In [181]:
# variance
np.var(val)

np.float64(20.909722222222218)

In [182]:
# Co-variance
np.cov(val)

array([[ 13.        ,   7.        ,  -6.5       , -27.5       ],
       [  7.        ,   6.33333333,  -5.16666667, -10.83333333],
       [ -6.5       ,  -5.16666667,   4.33333333,  11.16666667],
       [-27.5       , -10.83333333,  11.16666667,  64.33333333]])

# Find the minimum and maximum values in each column of a dataset.

In [183]:
arr = np.random.randint(1,20,12).reshape(4,3)
arr

array([[ 2,  8,  3],
       [ 2, 16,  9],
       [ 4, 17,  1],
       [ 4,  8, 17]], dtype=int32)

In [184]:
# min-column
col_min = np.min(arr,axis=0)
col_min

array([2, 8, 1], dtype=int32)

In [185]:
# max-column
col_max = np.max(arr,axis=0)
col_max

array([ 4, 17, 17], dtype=int32)

# Calculate the correlation coefficient between two NumPy arrays.

In [186]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])

np.corrcoef(x,y)        # correlation coefficient (x,y)

array([[1., 1.],
       [1., 1.]])

# Explain the use of `np.argmax()` and `np.argmin()` in analytics.

- np.argmax() → returns the index (position) of the maximum value

- np.argmin() → returns the index (position) of the minimum value

In [187]:
a = np.random.randint(1,20,12).reshape(4,3)
a

array([[ 3,  6, 11],
       [12,  5, 13],
       [ 9,  3,  6],
       [16,  4, 19]], dtype=int32)

In [188]:
np.argmax(a)

np.int64(11)

In [189]:
np.argmin(a)

np.int64(0)

# Round all values in a NumPy array to two decimal places.

In [190]:
f = np.arange(1,19,1.5,dtype=float).reshape(4,3)
f

array([[ 1. ,  2.5,  4. ],
       [ 5.5,  7. ,  8.5],
       [10. , 11.5, 13. ],
       [14.5, 16. , 17.5]])

In [191]:
np.round(f)

array([[ 1.,  2.,  4.],
       [ 6.,  7.,  8.],
       [10., 12., 13.],
       [14., 16., 18.]])

# Perform Z-score normalization on a dataset.

In [192]:
data = np.array([10, 20, 30, 40, 50])


mean = np.mean(data)
sd = np.std(data)

z = data - mean / sd
print("Z-score normalization:",z)

Z-score normalization: [ 7.87867966 17.87867966 27.87867966 37.87867966 47.87867966]
