##  Section 2: Indexing, Slicing & Masking (Q11–Q20)


In [1]:
import numpy as np

# Extract the last column from a 2D NumPy array.

In [2]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
a[:,3:]

array([[ 3],
       [ 7],
       [11]])

# Reverse a NumPy array without using loops.

In [4]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
b[::-1,::]

array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [6]:
b[::,::-1]

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8]])

# Explain boolean indexing and its importance in data analysis.

In [7]:
c = np.random.randint(1,100,25).reshape(5,5)
c

array([[ 6, 55,  4, 94, 80],
       [68, 97, 20, 38, 51],
       [31, 53, 45, 86, 65],
       [56, 71, 60, 65, 59],
       [78, 77, 64, 68, 10]], dtype=int32)

#### Boolean indexing is a technique used to filter, select, or modify data based on logical conditions (True / False). It is widely used in data analysis libraries such as Pandas and NumPy to work with subsets of data efficiently.

In [8]:
[c>50]

[array([[False,  True, False,  True,  True],
        [ True,  True, False, False,  True],
        [False,  True, False,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True, False]])]

# Select all values greater than the mean of an array.

In [9]:
m = np.mean(c)
print("mean:",m)
print("Values that are greater than mean:\n",c[c > m])

mean: 56.04
Values that are greater than mean:
 [94 80 68 97 86 65 71 60 65 59 78 77 64 68]


# Replace all negative values in an array with zero.

In [10]:
b = np.random.randint(-10,10,20).reshape(5,4)
b

array([[ -5,   0,  -5,   4],
       [  3,  -2,  -3,  -8],
       [ -7,   1,   3,  -1],
       [  7,  -3, -10,  -2],
       [ -4,   4,   7,   8]], dtype=int32)

In [11]:
b[b<0] = 0
b

array([[0, 0, 0, 4],
       [3, 0, 0, 0],
       [0, 1, 3, 0],
       [7, 0, 0, 0],
       [0, 4, 7, 8]], dtype=int32)

# Extract rows where total sales exceed a given threshold.

In [12]:
salary = np.array([10000,20000,400000,100000])

salary = salary[salary > 50000]
salary

array([400000, 100000])

# What is fancy indexing and how is it different from slicing?


- Fancy indexing in NumPy is a way to access array elements using an array or list of indices (or a boolean array), allowing selection of non-contiguous, arbitrary elements.

- Slicing, on the other hand, selects continuous ranges of elements using start:stop:step.

In [13]:
arr = np.array([10, 20, 30, 40, 50])

print("Slicing:",arr[1:4])        # Slicing → [20 30 40]
print("Fancy Indexing:",arr[[0, 2, 4]])  # Fancy indexing → [10 30 50]


Slicing: [20 30 40]
Fancy Indexing: [10 30 50]


# Select elements at indices `[2, 5, 8, 11]` from a NumPy array.

In [14]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [15]:
a[[2,5,8,11]]

array([ 2,  5,  8, 11])

# Demonstrate the difference between a view and a copy in NumPy.

- A view does not create new data. It only provides a different way to look at the same underlying array.

In [16]:
arr = np.array([10, 20, 30, 40, 50])

view_arr = arr[1:4]   # slicing → view
view_arr[0] = 999

print(arr)
print(view_arr)

[ 10 999  30  40  50]
[999  30  40]


# How do you apply multiple conditions when filtering a NumPy array?

In [17]:
arr = np.random.randint(-10,10,24).reshape(4,6)
arr

array([[  7,  -1,  -7,   7,   2,  -3],
       [ -2,  -9,  -4,   0,   8,   7],
       [ -3,   4,  -3,  -2,  -8,   4],
       [ -3,  -6,  -7,  -8, -10,   9]], dtype=int32)

In [18]:
result = arr[(arr>0) & (arr%2==0)]
result

array([2, 8, 4, 4], dtype=int32)