# Advance Indexing

In [39]:
import numpy as np

In [40]:
# Normal indexing and slicing

a = np.arange(24).reshape(6,4)

a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [41]:
# Indexing - [row,col]
a[1,2]

np.int64(6)

In [42]:
# Slicing [row:row,col:col]
a[1:,2:]

array([[ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

In [43]:
# Fancy Indexing
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [46]:
# fancyy indexing for row
a[[0,2,3,5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [50]:
# fancy indexing for column

a[:,[0,1,3]]

array([[ 0,  1,  3],
       [ 4,  5,  7],
       [ 8,  9, 11],
       [12, 13, 15],
       [16, 17, 19],
       [20, 21, 23]])

In [77]:
# Boolean Indexing

b = np.random.randint(1,100,24,dtype=np.int16).reshape(6,4)
b

array([[16, 31, 69, 64],
       [75, 83, 53, 57],
       [55, 43, 16, 22],
       [58, 12, 51,  9],
       [14, 61,  3, 64],
       [ 9, 67, 75,  6]], dtype=int16)

In [78]:
# Find all numbers greater than 50.

a[a>50]

array([70, 58, 79, 68, 74, 64], dtype=int32)

In [ ]:
# Find out all even numbers

a[a%2==0]

array([42, 70, 58, 10, 14, 34, 48, 24, 26, 68,  4, 36, 74, 64, 42, 16],
      dtype=int32)

In [92]:
# Find all numbers greater than 50 and even numbers

a[(a>50)&(a%2==0)]

array([70, 58, 68, 74, 64], dtype=int32)

In [96]:
# Find all number that are divisible by 5

a[(a%2 == 0)]

array([42, 70, 58, 10, 14, 34, 48, 24, 26, 68,  4, 36, 74, 64, 42, 16],
      dtype=int32)

In [102]:
# Find all numbers not divisible by 7

a[~(a%7 == 0)]

array([33, 58, 10, 34, 19, 48, 37, 79, 24, 41, 26, 68,  4, 36, 74, 64, 29,
       16], dtype=int32)