### Broadcasting

#### - Broadcasting describes that how numpy treats arrays with different shapes and arithematic operations
#### - Here, smaller array is 'broadcasted' with larger array for compatiable shape
 

In [1]:
import numpy as np

In [2]:
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)

print(a+b)      # Both have equal shapes of array for arithematic operationsb


[[ 6  8 10]
 [12 14 16]]


In [3]:
# Diff shape

a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)

print(a+b)

[[0 2 4]
 [3 5 7]]


### Broadcasting Rules:

#### 1. Ensure that two arrays have same number of dimensions.
##### - If the numbers of dimensions of the two arrays are different, add new dimensions with size 1 to the head of the array with the smaller dimensions.
#### 2. Make each dimensions of the two arrays the same size.
##### - If the sizes of each dimensions of the arrays do not match, dimensions with size 1 are stretched to the size of the other array.
##### - If there is a dimension whose size is not 1 in either of the two arrays, it cannot be broadcasted and an error is raised.

In [ ]:
# Examples

a = np.arange(12).reshape(4,3)
b = np.arange(3)

print(a)
print(b)

print(a+b) #broadcasting is done

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [7]:
a = np.arange(12).reshape(3,4)
b = np.arange(3)

print(a+b) # broadcasting will not happen

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [8]:
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)

print(a+b)


[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [12]:
a = np.arange(3).reshape(1,3)
b = np.arange(4).reshape(4,1)

print(a+b)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [13]:
a = np.array([1])
# shape (1,1)
b = np.arange(4).reshape(2,2)

print(a+b)

[[1 2]
 [3 4]]


In [ ]:
a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(4,3)


print(a+b)  # Error will occur bcoz 1 is not there, we cannot have broadcasting

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [ ]:
a = np.arange(16).reshape(4,4)
b = np.arange(4).reshape(2,2)

print(a+b) # shape is different 

ValueError: operands could not be broadcast together with shapes (4,4) (2,2) 