# Array Attribute

In [1]:
import numpy as np

In [2]:
a= np.array([12,3,4,5,6])
print(a)
print(type(a))

[12  3  4  5  6]
<class 'numpy.ndarray'>


In [3]:
a = np.arange(10)
b = np.arange(12,dtype=float).reshape(4,3)
c = np.arange(8).reshape(2,2,2)

In [4]:
a #1D array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
b # 2D / matrix array

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [6]:
c # tensor

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [7]:
# ndim - number of dimensions

print(f'Number of dimension: {a.ndim}')

Number of dimension: 1


In [8]:
# shape

print("Array",c)
print("Shape of array",c.shape)

Array [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
Shape of array (2, 2, 2)


In [9]:
# size 

print(b.size)
print(c.size)

12
8


In [10]:
# itemsize - Occupied size in memory

print(b.itemsize)

8


In [11]:
# dtype - type of data

print(a.dtype)
print(b.dtype)

int64
float64
