# Indexing

In [1]:
import numpy as np

In [2]:
a = np.arange(13)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### Note: [row,col] for indexing and slicing

In [4]:
# indexing

a[-1]

np.int64(12)

In [24]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
# 2D array indexing - [row,index]

b[0,1]

np.int64(1)

In [29]:
b[2,3]

np.int64(11)

In [32]:
# 3D - Tensor - [arr,row,index]

c = np.arange(8).reshape(2,2,2)
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [39]:
c[0,1,1]

np.int64(3)

In [41]:
# get the 6 from the tensor

c[1,1,0]

np.int64(6)

# Slicing

In [42]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [43]:
# slicing

a[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [57]:
a[2:5]

array([2, 3, 4])

In [55]:
a[0:13:2]

array([ 0,  2,  4,  6,  8, 10, 12])

In [44]:
# 2D- slicing
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [61]:
b[:,0]      #[row,col]

array([0, 4, 8])

In [92]:
b[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [91]:
b[1,::3]

array([4, 7])

In [69]:
b[1,1:3]

array([5, 6])

In [90]:
b[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [70]:
b[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [80]:
b[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [98]:
# 3D - slicing

d = np.arange(27).reshape(3,3,3)
d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [103]:
d[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [111]:
d[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [108]:
d[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [107]:
d[1,:,1]

array([10, 13, 16])

In [106]:
d[0,1]

array([3, 4, 5])

In [105]:
d[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])