## What is Numpy ?
##### - Numpy is scientific computing library of python.
##### - Numpy is core library for Pandas, SciPy, TensorFlow and etc.
##### - Numpy arrays are convinent for maths calculations.
##### - It consist of homogenous(same) data types  

------------------------------------------------------------------------------------------------------------------
## Difference between Sequence & Array
##### - Array consumes less memory space & store large amount of data..
##### - Array can perform mathematical calculations faster as compared to sequence.
##### - Numpy arrays are fixed in size, list are dynamic in size.

---------------------------------------
# Creating numpy arrays


In [11]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [12]:
# import library
import numpy as np

In [13]:
# np.array

a = np.array([1,2,3,4])     # 1D array
print(type(a))
a

<class 'numpy.ndarray'>


array([1, 2, 3, 4])

In [14]:
# 2D & 3D

a = np.array([[1,2,3,4],[5,6,7,8]])   # [[]] - defines the 2d array
print("2D array:\n",a)


b = np.array([[[1,2,],[3,4]],[[5,6],[7,8]]])     # [[[]]] - defines the 3d array 
print("3D array:\n",b)

2D array:
 [[1 2 3 4]
 [5 6 7 8]]
3D array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [15]:
#dtype

a = np.array([1,2,3,4,5,6,7])
a.dtype     # data type of array

dtype('int64')

In [16]:
a = np.array([1,2,3,4],dtype=complex) # complex
b = np.array([1,2,3,4],dtype=float) # float
c = np.array([1,2,3,4],dtype=bool) # bool

print("complex:",a)
print("float:",b)
print("bool:",c)


complex: [1.+0.j 2.+0.j 3.+0.j 4.+0.j]
float: [1. 2. 3. 4.]
bool: [ True  True  True  True]


In [17]:
# arange - It gives random number from given range

a = np.arange(1,5)
print(a)
b = np.arange(1,5,2)
print(b)


[1 2 3 4]
[1 3]


In [18]:
# With reshape - Product should be equal to number of items in array 

np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [19]:
# np.ones and np.zeros - Used in nueral networks

np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
# np.random

np.random.random((3,3))

array([[0.51983618, 0.78904064, 0.61962915],
       [0.65058315, 0.78716282, 0.5880404 ],
       [0.6769559 , 0.84910342, 0.30132478]])

In [28]:
# np.linspace -linearly space/ linear space

a = np.linspace(1,10,15)  # 3rd index shows how many number we want
print(a,'\n')

b = np.linspace(1,10,10,dtype=int)
print(b)

[ 1.          1.64285714  2.28571429  2.92857143  3.57142857  4.21428571
  4.85714286  5.5         6.14285714  6.78571429  7.42857143  8.07142857
  8.71428571  9.35714286 10.        ] 

[ 1  2  3  4  5  6  7  8  9 10]


In [23]:
# np.identity - used for identity matrix

np.identity(3)  # diagonal items are 1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])