# Array Functions

In [124]:
import numpy as np

In [ ]:
a = np.random.random((3,3))
a = np.round(a*100)
a

array([[19., 17.,  9.],
       [36., 40., 99.],
       [67., 89., 18.]])

In [126]:
# max

np.max(a)

np.float64(99.0)

In [127]:
# min

np.min(a)

np.float64(9.0)

In [128]:
# sum

np.sum(a)

np.float64(394.0)

In [129]:
# prod

np.prod(a)

np.float64(44481562361280.0)

In [135]:
# col - 0, row - 1

print('row-wise:',np.max(a,axis=1))   
print('col-wise:',np.min(a,axis=0))

row-wise: [19. 99. 89.]
col-wise: [19. 17.  9.]


In [139]:
# mean

np.mean(a)

np.float64(43.77777777777778)

In [140]:
# median

np.median(a)

np.float64(36.0)

In [141]:
# std

np.std(a)

np.float64(31.470542761897114)

In [142]:
# var

np.var(a)

np.float64(990.3950617283949)

In [143]:
# trigonomteric function - not used in data science

np.sin(a)

array([[ 0.14987721, -0.96139749,  0.41211849],
       [-0.99177885,  0.74511316, -0.99920683],
       [-0.85551998,  0.86006941, -0.75098725]])

In [ ]:
# dot product

a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12).reshape(4,3)

np.dot(a1,a2)

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

In [158]:
# log 

c = np.log(a)

c

array([[2.94443898, 2.83321334, 2.19722458],
       [3.58351894, 3.68887945, 4.59511985],
       [4.20469262, 4.48863637, 2.89037176]])

In [154]:
# exponent

np.exp(a)

array([[1.78482301e+08, 2.41549528e+07, 8.10308393e+03],
       [4.31123155e+15, 2.35385267e+17, 9.88903032e+42],
       [1.25236317e+29, 4.48961282e+38, 6.56599691e+07]])

In [159]:
# round

np.round(c)

array([[3., 3., 2.],
       [4., 4., 5.],
       [4., 4., 3.]])

In [ ]:
# floor

np.floor(c)

array([[2., 2., 2.],
       [3., 3., 4.],
       [4., 4., 2.]])

In [ ]:
# ceil

np.ceil(c)

array([[3., 3., 3.],
       [4., 4., 5.],
       [5., 5., 3.]])