### Numpy Tricks

### np.sort

In [210]:
import numpy as np

In [211]:
a = np.random.randint(1,50,25)
a

array([26, 38, 14, 29,  8,  6,  3, 10, 23, 49, 49, 47, 35, 15, 36, 43,  9,
       40, 31, 35, 40, 37, 22, 25, 22], dtype=int32)

In [212]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[ 3, 25, 42, 73],
       [24,  4, 88, 97],
       [77, 18, 62, 94],
       [84,  9,  5, 10],
       [ 9, 94, 12, 59],
       [46,  5, 94, 36]], dtype=int32)

In [213]:
np.sort(a)

array([ 3,  6,  8,  9, 10, 14, 15, 22, 22, 23, 25, 26, 29, 31, 35, 35, 36,
       37, 38, 40, 40, 43, 47, 49, 49], dtype=int32)

In [214]:
np.sort(a)[::-1]         # slicing for 1D to reverse array

array([49, 49, 47, 43, 40, 40, 38, 37, 36, 35, 35, 31, 29, 26, 25, 23, 22,
       22, 15, 14, 10,  9,  8,  6,  3], dtype=int32)

In [215]:
np.sort(b,axis=0)       # axis=0 --> column(index)

array([[ 3,  4,  5, 10],
       [ 9,  5, 12, 36],
       [24,  9, 42, 59],
       [46, 18, 62, 73],
       [77, 25, 88, 94],
       [84, 94, 94, 97]], dtype=int32)

### np.append
#### - appends the value at the end of the array

In [216]:
np.append(a,100)

array([ 26,  38,  14,  29,   8,   6,   3,  10,  23,  49,  49,  47,  35,
        15,  36,  43,   9,  40,  31,  35,  40,  37,  22,  25,  22, 100])

In [217]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

# b.shape is --> row, 1 --> add one

array([[ 3., 25., 42., 73.,  1.],
       [24.,  4., 88., 97.,  1.],
       [77., 18., 62., 94.,  1.],
       [84.,  9.,  5., 10.,  1.],
       [ 9., 94., 12., 59.,  1.],
       [46.,  5., 94., 36.,  1.]])

In [218]:
b.shape

(6, 4)

In [219]:
np.append(b,np.zeros((1,b.shape[1])),axis=0)

# b.shape is --> col, 0 --> add one
# shape[2] --> depth (3D arrays)

array([[ 3., 25., 42., 73.],
       [24.,  4., 88., 97.],
       [77., 18., 62., 94.],
       [84.,  9.,  5., 10.],
       [ 9., 94., 12., 59.],
       [46.,  5., 94., 36.],
       [ 0.,  0.,  0.,  0.]])

### np.concatenate

In [220]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [221]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [222]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

In [223]:
t = np.array([1,2,3,4,2,1,12,4,5])

np.unique(t)

array([ 1,  2,  3,  4,  5, 12])

### np.expand_dims
#### -  we can get expanded dims of array

In [224]:
a.shape

(25,)

In [225]:
z = np.expand_dims(a,axis=0)
z.shape


(1, 25)

In [226]:
x = np.expand_dims(a,axis=1)
x.shape

(25, 1)

### np.where
#### - returns the indices of input arrays

In [227]:
a

array([26, 38, 14, 29,  8,  6,  3, 10, 23, 49, 49, 47, 35, 15, 36, 43,  9,
       40, 31, 35, 40, 37, 22, 25, 22], dtype=int32)

In [228]:
np.where(a>25)       # gets the index position where condition is passed

(array([ 0,  1,  3,  9, 10, 11, 12, 14, 15, 17, 18, 19, 20, 21]),)

In [229]:
np.where(a>35,a,0)

array([ 0, 38,  0,  0,  0,  0,  0,  0,  0, 49, 49, 47,  0,  0, 36, 43,  0,
       40,  0,  0, 40, 37,  0,  0,  0], dtype=int32)

In [230]:
np.where(a>40,1,0)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0])

### np.argmax --> argument max

In [231]:
np.argmax(a)  # gives the max number's index

np.int64(9)

In [232]:
# argmin 

np.argmin(a)

np.int64(6)

### np.cumsum 
#### Function is used when we want to compute the cumulative sum of array over a axis

In [233]:
np.cumsum(a)

array([ 26,  64,  78, 107, 115, 121, 124, 134, 157, 206, 255, 302, 337,
       352, 388, 431, 440, 480, 511, 546, 586, 623, 645, 670, 692])

In [234]:
b

array([[ 3, 25, 42, 73],
       [24,  4, 88, 97],
       [77, 18, 62, 94],
       [84,  9,  5, 10],
       [ 9, 94, 12, 59],
       [46,  5, 94, 36]], dtype=int32)

In [235]:
np.cumsum(b,axis=0) # 0 --> col 

array([[  3,  25,  42,  73],
       [ 27,  29, 130, 170],
       [104,  47, 192, 264],
       [188,  56, 197, 274],
       [197, 150, 209, 333],
       [243, 155, 303, 369]])

In [236]:
np.cumprod(a)

array([                  26,                  988,                13832,
                     401128,              3209024,             19254144,
                   57762432,            577624320,          13285359360,
               650982608640,       31898147823360,     1499212947697920,
          52472453169427200,   787086797541408000, -8558363435928415232,
         925253729269177344,  8327283563422596096,  1049949210131914752,
       -4345062633329745920, -4503239576864694272,  4337857662507745280,
       -5519963150599389184,  7688019202780299264,  7733039332411965440,
        4106168649677275136])

In [237]:
# np.percentile
print(a)

np.percentile(a,75)

[26 38 14 29  8  6  3 10 23 49 49 47 35 15 36 43  9 40 31 35 40 37 22 25
 22]


np.float64(38.0)

### np.histogram --> Shows the frequency of numbers

In [238]:
a
np.histogram(a,bins=[0,5,10,15,20,25,30,35])

(array([1, 3, 2, 1, 3, 3, 3]), array([ 0,  5, 10, 15, 20, 25, 30, 35]))

### np.corrcoef --> Return pearson product-moment correlation coefficients


In [239]:
salary = np.array([350000,800000,1500000,2500000])
age = np.array([1,5,10,15])

np.corrcoef(salary,age)

array([[1.       , 0.9920757],
       [0.9920757, 1.       ]])

### np.isin --> checks for the values in array-1 is present in anotherm comparing array or not.

In [240]:
a = np.random.randint(1,25,10)
b = np.random.randint(1,25,10)

In [241]:
np.isin(a,b,)

array([ True, False, False, False, False, False, False, False, False,
       False])

### np.flip 
##### --> reverses the order of array elements along the specified axis, preserving the shape of the array

In [242]:
a


array([24, 19,  2, 21,  4,  9, 10,  9, 22, 23], dtype=int32)

In [244]:
np.flip(a)

array([23, 22,  9, 10,  9,  4, 21,  2, 19, 24], dtype=int32)

In [247]:
b = np.arange(12).reshape(3,4)
b


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.flip(b,axis=0) #0 --> col

array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

### np.put
##### replaces specific element of array with another element and changes it permanently

In [256]:
a

# np.put(a,[0,1],[1,2])


array([ 1,  2,  2, 21,  4,  9, 10,  9, 22, 23], dtype=int32)

### np.delete

In [260]:
np.delete(a,2)

array([ 1,  2, 21,  4,  9, 10,  9, 22, 23], dtype=int32)

### Set Functions

In [266]:
a = np.array([1,2,3,4,5])
b = np.array([6,2,3,9,10])

In [269]:
# union1d

np.union1d(a,b)     # all elements without duplicates

array([ 1,  2,  3,  4,  5,  6,  9, 10])

In [270]:
# intersect1d

np.intersect1d(a,b)     # common elements from both intersects

array([2, 3])

In [271]:
# setdiff1d

np.setdiff1d(a,b)

array([1, 4, 5])

In [272]:
np.setdiff1d(b,a)

array([ 6,  9, 10])

In [273]:
# np.setxor1d

np.setxor1d(a,b)    # removes common element

array([ 1,  4,  5,  6,  9, 10])

### np.clip
##### Clip(limit) the values in an array 


In [ ]:
a = np.arange(1,100)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
x = np.clip(a,a_min=20,a_max=90)

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
       20, 20, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90])