# Array Operators

In [1]:
import numpy as np

In [14]:
# Assign the array

a = np.arange(12).reshape(3,4)
b = np.arange(1,13).reshape(4,3)

print(b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# Scalar Operation

# Arithematic operator - Addition

plus = 2 + a
print("Adition\n",plus) 

Adition
 [[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [22]:
# Arithematic - Exponential

expo = 2 ** b
print("Exponential\n",expo)

Exponential
 [[   2    4    8]
 [  16   32   64]
 [ 128  256  512]
 [1024 2048 4096]]


In [ ]:
# Relational 

# greater

greater = b > 5
print(greater)


[[False False False]
 [False False  True]
 [ True  True  True]
 [ True  True  True]]


In [27]:
# Equal to

equal = (a == 10)
print(equal)


[[False False False False]
 [False False False False]
 [False False  True False]]


In [ ]:
# Vector operations

# Arithmetic - Addition

add = a + (b.reshape(3,4))

print(add)

[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]]


In [ ]:
# arithmetic - subtration

sub = a.reshape(4,3) - b

sub

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])